import type { Metadata } from 'next'
import './globals.css'
import { GeistSans } from 'geist/font/sans'
import Providers from './components/providers'
import Navigation from './components/navigation'
import { twMerge } from 'tailwind-merge'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={GeistSans.className}>
        <Providers>
          <div className="flex flex-col min-h-screen">
            <div
              className={twMerge(
                'flex-1 bg-white text-black',
                'dark:bg-black dark:text-white'
              )}
            >
              <Navigation />
              <div className='container mx-auto'>{children}</div>
            </div>
          </div>
        </Providers>
      </body>
    </html>
  )
}
